version: "3.9"
services:
  web:
    build: .
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      # Variables pour le développement local
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=mysql
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - .:/app
      - ./storage:/app/storage
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
       