version: "3.9"
services:
  web:
    build: .
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=laravel-next-db.cv8k2qmmo9ic.eu-north-1.rds.amazonaws.com
      - DB_PORT=3306
      - DB_DATABASE=laravel_next_db
      - DB_USERNAME=admin
      - DB_PASSWORD=Shakaponk-65
       